# Generated by Django 3.1 on 2020-08-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_participantreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookchat',
            name='characters_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookchat',
            name='links_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookchat',
            name='message_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookchat',
            name='photos_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookchat',
            name='reactions_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facebookchat',
            name='gifs_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participantreaction',
            name='counts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
    ]
