# Generated by Django 3.1 on 2020-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20200826_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookchat',
            name='participants_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
