# Generated by Django 3.1 on 2020-08-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_facebookchat_participants_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookchat',
            old_name='message_number',
            new_name='messages_number',
        ),
        migrations.AddField(
            model_name='participant',
            name='characters_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='gifs_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='links_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='messages_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='photos_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
