# Generated by Django 3.1 on 2020-09-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_auto_20200827_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='words_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
