# Generated by Django 3.1 on 2020-09-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_participant_words_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='participant',
        ),
        migrations.DeleteModel(
            name='ParticipantReaction',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
