# Generated by Django 3.1 on 2020-09-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_auto_20200915_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='counts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='reaction',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
