# Generated by Django 3.1 on 2020-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20200915_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='counts',
            new_name='counter_most_common_react',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='reaction',
            new_name='most_common_reaction',
        ),
        migrations.AddField(
            model_name='participant',
            name='total_numbers_of_reactions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
