# Generated by Django 3.1 on 2020-10-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_auto_20200915_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
