# Generated by Django 3.1 on 2020-10-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenAndMoreCharWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=25)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
        migrations.CreateModel(
            name='SixCharWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=6)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
        migrations.CreateModel(
            name='SevenCharWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=7)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
        migrations.CreateModel(
            name='NineCharWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=9)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
        migrations.CreateModel(
            name='FourCharWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=4)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
        migrations.CreateModel(
            name='FiveCharWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=5)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
        migrations.CreateModel(
            name='EighthCharWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=8)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.participant')),
            ],
        ),
    ]
