# Generated by Django 3.1 on 2020-10-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0011_eighthcharword_fivecharword_fourcharword_ninecharword_sevencharword_sixcharword_tenandmorecharword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenandmorecharword',
            name='word',
            field=models.CharField(max_length=500),
        ),
    ]
