# Generated by Django 3.1 on 2020-10-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0012_auto_20201012_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EighthCharWord',
            new_name='EightCharWord',
        ),
    ]
