# Generated by Django 3.1 on 2020-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0014_auto_20201019_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eightcharword',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eightcharword',
            name='word',
            field=models.CharField(default='-', max_length=8),
        ),
        migrations.AlterField(
            model_name='fivecharword',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fivecharword',
            name='word',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='fourcharword',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fourcharword',
            name='word',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='ninecharword',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ninecharword',
            name='word',
            field=models.CharField(default='-', max_length=9),
        ),
        migrations.AlterField(
            model_name='sevencharword',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sevencharword',
            name='word',
            field=models.CharField(default='-', max_length=7),
        ),
        migrations.AlterField(
            model_name='sixcharword',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sixcharword',
            name='word',
            field=models.CharField(default='-', max_length=6),
        ),
        migrations.AlterField(
            model_name='tenandmorecharword',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenandmorecharword',
            name='word',
            field=models.CharField(default='-', max_length=40),
        ),
    ]
